---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
  name: {{ .Values.name }}
  finalizers:
    - inferenceservice.finalizers
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  transformer:
    containers:
      - args:
        - '--predictor_host'
        - music-predictor-openmusicai2.apps.dev.rhoai.rh-aiservices-bu.com
        - '--predictor_protocol'
        - v2
        - '--predictor_use_ssl'
        - 'True'
          # - '--feast_serving_url'
          # - 'feature-server-service.default.svc.cluster.local:6566'
          # - --'feature_service'
          # - song_properties_fs
          # - '--entity_id_name'
          # - music
          # - '--feature_refs'
          # - 'song_properties:is_explicit'
          # - 'song_properties:duration_ms'
          # - 'song_properties:danceability'
          # - 'song_properties:energy'
          # - 'song_properties:key'
          # - 'song_properties:loudness'
          # - 'song_properties:mode'
          # - 'song_properties:speechiness'
          # - 'song_properties:acousticness'
          # - 'song_properties:instrumentalness'
          # - 'song_properties:liveness'
          # - 'song_properties:valence'
          # - 'song_properties:tempo'
        command:
          - python
          - '-m'
          - music_transformer
        image: quay.io/rlundber/music_transformer:0.4
        name: kserve-container
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi
  predictor:
    maxReplicas: 0
    minReplicas: 1
    model:
      modelFormat:
        name: onnx
        version: '1'
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      runtime: {{ .Values.name }}
      storage:
        key: {{ .Values.model_s3_secret | default "aws-connection-models" }}
        path: {{ .Values.model_path }}/{{ .Values.model_version }}
