---
apiVersion: v2
description: A little Helm chart for Data Science Pipeline Application ğŸˆ
name: dspa
version: 0.0.4
home: https://rhoai-mlops.github.io/mlops/
maintainers:
  - name: RHRolun
  - name: rcarrata
  - name: ckavili