---
apiVersion: v2
description: A Helm chart for alerts and notification config ðŸš¨
name: alerting
version: 0.0.1
home: https://rhoai-mlops.github.io/mlops/
maintainers:
  - name: RHRolun
  - name: rcarrata
  - name: ckavili