---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ct-trigger-template
spec:
  params:
    - name: gitrepositoryurl
      description: The git repository url
    - name: git-revision
      description: The git revision
      default: main
    - name: git-ref
      description: The full git ref
      default: master
    - name: git-repo-name
      description: The name of the deployment to be created / patched
    - name: git-branch
      description: The git branch name
    - name: git-short-revision
      description: Seven character git sha
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ct-pipeline-
      spec:
        pipelineRef:
          name: ct-pipeline
        params:
          - name: APPLICATION_NAME
            value: $(tt.params.git-repo-name)
          - name: GIT_URL
            value: $(tt.params.gitrepositoryurl)
          - name: GIT_REVISION
            value: $(tt.params.git-revision)
          - name: GIT_SHORT_REVISION
            value: $(tt.params.git-short-revision)
          - name: GIT_REF
            value: $(tt.params.git-ref)
          - name: GIT_BRANCH
            value: $(tt.params.git-branch)
        workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: shared-workspace